services:
    pico.autodbbackup.cron.task.core.auto_db_backup:
        class: pico\autodbbackup\cron\task\auto_db_backup
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@dbal.tools'
            - '@log'
            - '@user'
            - '@service_container'            
            - '%core.root_path%'
            - '%core.php_ext%'
        calls:
            - [set_name, [pico.autodbbackup.cron.task.auto_db_backup]]
        tags:
            - { name: cron.task }
