imports:
    - { resource: tables.yml }
services:
    flerex.linkedaccounts.listener:
        class: flerex\linkedaccounts\event\main_listener
        arguments:
            - '@auth'
            - '@user'
            - '@request'
            - '@config'
            - '@template'
            - '@controller.helper'
            - '@flerex.linkedaccounts.linking_service'
            - '@flerex.linkedaccounts.auth_service'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
    flerex.linkedaccounts.linking_service:
        class: flerex\linkedaccounts\service\linking_service
        arguments:
            - '@user'
            - '@config'
            - '@dbal.conn'
            - '%flerex.linkedaccounts.tables.links%'
    flerex.linkedaccounts.auth_service:
        class: flerex\linkedaccounts\service\auth_service
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@config'
            - '@user'
    flerex.linkedaccounts.switcher:
        class: flerex\linkedaccounts\controller\switcher
        arguments:
            - '@user'
            - '@auth'
            - '@config'
            - '@request'
            - '@symfony_request'
            - '@controller.helper'
            - '@flerex.linkedaccounts.linking_service'
            - '%core.root_path%'
            - '%core.php_ext%'
